// src/features/CaThucHanh/action.js
export const ACTIONS = {
    // Load Data
    LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
    LOAD_DATA_ERROR: 'LOAD_DATA_ERROR',
    // Table Interaction
    SET_PAGINATION: 'SET_PAGINATION',
    SET_SORT: 'SET_SORT',
    SET_SELECTION: 'SET_SELECTION',
    UPDATE_DISPLAYED_DATA: 'UPDATE_DISPLAYED_DATA',
};