// src/features/labManagement/actions.js
export const ACTIONS = {
    // Load Data
    LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
    LOAD_DATA_ERROR: 'LOAD_DATA_ERROR',
    // Table Interaction
    SET_SEARCH: 'SET_SEARCH',
    SET_SEARCH_COLUMN: 'SET_SEARCH_COLUMN',
    SEARCH_START: 'SEARCH_START',
    SEARCH_COMPLETE: 'SEARCH_COMPLETE',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    SET_PAGINATION: 'SET_PAGINATION',
    SET_SORT: 'SET_SORT',
    SET_SELECTION: 'SET_SELECTION',
    UPDATE_DISPLAYED_DATA: 'UPDATE_DISPLAYED_DATA',
    // Delete
    DELETE_START: 'DELETE_START',
    DELETE_COMPLETE: 'DELETE_COMPLETE',
    // QR Modal
    SHOW_QR_MODAL_START: 'SHOW_QR_MODAL_START',
    SHOW_QR_MODAL_SUCCESS: 'SHOW_QR_MODAL_SUCCESS',
    SHOW_QR_MODAL_ERROR: 'SHOW_QR_MODAL_ERROR',
    HIDE_QR_MODAL: 'HIDE_QR_MODAL',
    // User Profile Modal
    LOAD_USER_PROFILE_START: 'LOAD_USER_PROFILE_START',
    LOAD_USER_PROFILE_SUCCESS: 'LOAD_USER_PROFILE_SUCCESS',
    LOAD_USER_PROFILE_ERROR: 'LOAD_USER_PROFILE_ERROR',
    UPDATE_USER_PROFILE_START: 'UPDATE_USER_PROFILE_START',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_ERROR: 'UPDATE_USER_PROFILE_ERROR',
    HIDE_USER_PROFILE_MODAL: 'HIDE_USER_PROFILE_MODAL',
    // Status Modal
    SHOW_STATUS_MODAL: 'SHOW_STATUS_MODAL',
    HIDE_STATUS_MODAL: 'HIDE_STATUS_MODAL',
    LOAD_COMPUTERS_START: 'LOAD_COMPUTERS_START',
    LOAD_COMPUTERS_SUCCESS: 'LOAD_COMPUTERS_SUCCESS',
    LOAD_COMPUTERS_ERROR: 'LOAD_COMPUTERS_ERROR',
    LOAD_DEVICE_TYPES_START: 'LOAD_DEVICE_TYPES_START',
    LOAD_DEVICE_TYPES_SUCCESS: 'LOAD_DEVICE_TYPES_SUCCESS',
    LOAD_DEVICE_TYPES_ERROR: 'LOAD_DEVICE_TYPES_ERROR',
    LOAD_DEVICES_BY_TYPE_START: 'LOAD_DEVICES_BY_TYPE_START',
    LOAD_DEVICES_BY_TYPE_SUCCESS: 'LOAD_DEVICES_BY_TYPE_SUCCESS',
    LOAD_DEVICES_BY_TYPE_ERROR: 'LOAD_DEVICES_BY_TYPE_ERROR',
    SET_STATUS_MODAL_TAB: 'SET_STATUS_MODAL_TAB',
    // Computer Update Modal
    SHOW_COMPUTER_UPDATE_MODAL: 'SHOW_COMPUTER_UPDATE_MODAL',
    HIDE_COMPUTER_UPDATE_MODAL: 'HIDE_COMPUTER_UPDATE_MODAL',
    TOGGLE_COMPUTER_UPDATE_SELECTION: 'TOGGLE_COMPUTER_UPDATE_SELECTION',
    UPDATE_COMPUTER_STATUS_START: 'UPDATE_COMPUTER_STATUS_START',
    UPDATE_COMPUTER_STATUS_COMPLETE: 'UPDATE_COMPUTER_STATUS_COMPLETE',
    // Device Update Modal
    SHOW_DEVICE_UPDATE_MODAL: 'SHOW_DEVICE_UPDATE_MODAL',
    HIDE_DEVICE_UPDATE_MODAL: 'HIDE_DEVICE_UPDATE_MODAL',
    TOGGLE_DEVICE_UPDATE_SELECTION: 'TOGGLE_DEVICE_UPDATE_SELECTION',
    UPDATE_DEVICE_STATUS_START: 'UPDATE_DEVICE_STATUS_START',
    UPDATE_DEVICE_STATUS_COMPLETE: 'UPDATE_DEVICE_STATUS_COMPLETE',
};

// Trạng thái thiết bị/máy tính
export const BROKEN_STATUS = 'Đã hỏng';
export const ACTIVE_STATUS = 'Đang hoạt động';
export const INACTIVE_STATUS = 'Không hoạt động';